# Generated by Django 4.2.2 on 2024-06-07 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MicroMarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estates.city')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_location', models.CharField(max_length=255)),
                ('parcel_size_acres', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_acre', models.DecimalField(decimal_places=2, max_digits=10)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estates.broker')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estates.city')),
                ('micro_market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estates.micromarket')),
            ],
        ),
    ]
